/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./demo/demo.cjs]{@link ./demo/demo.cjs}
 * 
 **/
import {showHelp}  from "../esm/index.mjs";


(async function ()
{
    await showHelp("", {
        windowTitle: "❔" + " Help ",
        topText: "Press CTRL + C or Q to Quit | Page Down to scroll down | Any key to next line",
        topTextBg: "",
        topTextReversed: true,
        colorify: true,
        markdown: true,
        filepath: "./demo/random-text.md"
    });
}())